version: '3.9'

services:
  web:
    build:
      context: ../django_app # remplace par le vrai chemin relatif
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ../django_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
